### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by 0xzz** [CFN-softbio/SciAnalysis#1]
Is there a specific reason why Examples are being left out?

**Comment by jrmlhermitte** [comment]
no, it would be nice if they could be added in. do you have any?

**Comment by 0xzz** [comment]
Kevin gave me his most update-to-date codes, including examples, which look pretty comprehensive. I'll merge them in soon. I'll probably contribute some of my own processing examples as well (needs some tidying).

**Comment by 0xzz** [comment]
I merged Kevin's examples into the repo. Issue closed.
