### ISSUE TITLE
ERROR (ModuleNotFoundError) with running BCP example

### ISSUE THREAD

**Issue by FPowala** [CFN-softbio/SciAnalysis#22]
While testing the software (runIm-BCP) I get the following console data:
Considering: ./ (2 subdirs, 3 files)
Considering: ./.idea (1 subdirs, 4 files)
Considering: ./.idea\inspectionProfiles (0 subdirs, 1 files)
Considering: ./data (1 subdirs, 7 files)
Running fft for C67 on Dow 55_q07
  ERROR (ModuleNotFoundError) with file ./data\C67 on Dow 55_q07.jpg.

Process finished with exit code 0

Since there is no more information about which one is missing I consider it a bug. I got all packages listed in requirements installed.

**Comment by kevinyager** [comment]
Thanks. I just pushed a fix.
