### ISSUE TITLE
Should make into a package

### ISSUE THREAD

**Issue by jrmlhermitte** [CFN-softbio/SciAnalysis#7]
It would be nice is SciAnalysis could be made into a package. I started a bit here:
https://github.com/CFN-softbio/SciAnalysis/tree/improved

It's fairly easy, just needs agreement. @0xzz

**Comment by jrmlhermitte** [comment]
oops I already made those changes.
anyway, when it's ready, we should remove calls that add the SciAnalysis location to the python path and rather import globally
(and we should push this to the nsls 2 conda channel)

**Comment by 0xzz** [comment]
I agree. It would be nice to package this into an easily install-able module. We can put it on both conda-forge channel and PyPI.

**Comment by kevinyager** [comment]
TBD. This should be quick/easy. Anyone who wants to do this and test the outcome, please go ahead.
